import type { Metadata } from "next";
import "./globals.css";
import MyLayout from "@/app/layout/MyLayout";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
	title: "SMU Module Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<MyLayout>
					{children}
				</MyLayout>
				<Toaster 
					position="bottom-center"
					toastOptions={{
						className: '',
						duration: 5000,
						removeDelay: 500,
					}}/>
			</body>
		</html>
	);
}
